import type { Post, SocialAccount, Template } from "@/types";

export const mockAccounts: SocialAccount[] = [
  { id: "acc-1", provider: "twitter", username: "@tamiyoung", profileImage: "" },
  { id: "acc-2", provider: "instagram", username: "tami.young", profileImage: "" },
  { id: "acc-3", provider: "linkedin", username: "Tami Young", profileImage: "" },
];

export const mockPosts: Post[] = [
  {
    id: "post-1",
    platform: "twitter",
    content: "The biggest myth in content creation? That you need to post every day.\n\nThe truth: One high-quality post that sparks conversation > 7 forgettable ones.\n\nHere's what I learned after growing to 50K followers with just 3 posts per week:",
    publishedAt: "2025-02-20T14:30:00Z",
    likes: 2847,
    comments: 342,
    shares: 891,
    impressions: 156000,
    reach: 98000,
    engagementRate: 8.2,
    isTopPerformer: true,
    accountUsername: "@tamiyoung",
  },
  {
    id: "post-2",
    platform: "linkedin",
    content: "I just turned down a $50K brand deal.\n\nNot because the money wasn't good — it was great.\n\nBut here's why I said no:\n\nThe brand didn't align with my audience's values. My followers trust me because I only recommend what I genuinely believe in.\n\nShort-term gain, long-term pain.\n\nYour audience's trust is your most valuable currency. Protect it at all costs.",
    publishedAt: "2025-02-18T09:00:00Z",
    likes: 4521,
    comments: 687,
    shares: 1203,
    impressions: 234000,
    reach: 145000,
    engagementRate: 9.1,
    isTopPerformer: true,
    accountUsername: "Tami Young",
  },
  {
    id: "post-3",
    platform: "instagram",
    content: "POV: You stopped chasing algorithms and started creating for YOUR people.\n\nResult? My engagement went up 300% in 30 days.\n\n5 things I changed:\n1. Wrote like I'm texting my best friend\n2. Shared real failures, not just wins\n3. Asked questions in every caption\n4. Responded to every comment for 1 hour\n5. Stopped posting what everyone else posts",
    publishedAt: "2025-02-15T17:00:00Z",
    likes: 8932,
    comments: 1247,
    shares: 2341,
    impressions: 412000,
    reach: 287000,
    engagementRate: 12.4,
    isTopPerformer: true,
    accountUsername: "tami.young",
  },
  {
    id: "post-4",
    platform: "twitter",
    content: "Unpopular opinion: Your content strategy doesn't need to be complicated.\n\nPick 3 topics.\nPost 3-5x per week.\nEngage for 30 min daily.\n\nThat's it. The rest is just noise.",
    publishedAt: "2025-02-12T11:15:00Z",
    likes: 1923,
    comments: 256,
    shares: 543,
    impressions: 89000,
    reach: 62000,
    engagementRate: 6.8,
    isTopPerformer: true,
    accountUsername: "@tamiyoung",
  },
  {
    id: "post-5",
    platform: "linkedin",
    content: "After 3 years of building my personal brand, here are 7 uncomfortable truths:\n\n1. Nobody cares about your credentials. They care about your stories.\n2. Consistency beats creativity 99% of the time.\n3. Your first 100 posts will be terrible. Post them anyway.\n4. Engagement pods are a waste of time.\n5. The best content comes from real conversations.\n6. You don't need a niche. You ARE the niche.\n7. If you're not slightly embarrassed by what you posted, you're not being vulnerable enough.\n\nWhich one resonates most? Drop the number below.",
    publishedAt: "2025-02-10T08:30:00Z",
    likes: 6234,
    comments: 892,
    shares: 1567,
    impressions: 298000,
    reach: 201000,
    engagementRate: 10.3,
    isTopPerformer: true,
    accountUsername: "Tami Young",
  },
  {
    id: "post-6",
    platform: "instagram",
    content: "Save this for when you need caption ideas:\n\n• Start with a bold statement\n• Ask a controversial question\n• Share a personal failure\n• Give a mini-tutorial\n• Use \"POV:\" format\n• Tell a story in 3 sentences\n• Share a before/after\n\nBookmark this. You'll thank me later.",
    publishedAt: "2025-02-08T16:45:00Z",
    likes: 5421,
    comments: 432,
    shares: 3210,
    impressions: 267000,
    reach: 189000,
    engagementRate: 7.6,
    isTopPerformer: true,
    accountUsername: "tami.young",
  },
  {
    id: "post-7",
    platform: "twitter",
    content: "Just hit 50K followers.\n\nHere's the tweet that changed everything for me:\n\nI stopped trying to go viral and started trying to be useful.\n\nThat's it. That's the strategy.",
    publishedAt: "2025-02-05T13:00:00Z",
    likes: 987,
    comments: 145,
    shares: 234,
    impressions: 45000,
    reach: 32000,
    engagementRate: 4.9,
    isTopPerformer: false,
    accountUsername: "@tamiyoung",
  },
  {
    id: "post-8",
    platform: "linkedin",
    content: "Hot take: Most \"content strategies\" are just copying what worked for someone else.\n\nBut their audience isn't your audience.\nTheir story isn't your story.\nTheir timing isn't your timing.\n\nStop copying. Start experimenting.",
    publishedAt: "2025-02-03T10:00:00Z",
    likes: 2100,
    comments: 312,
    shares: 445,
    impressions: 112000,
    reach: 78000,
    engagementRate: 5.4,
    isTopPerformer: false,
    accountUsername: "Tami Young",
  },
  {
    id: "post-9",
    platform: "instagram",
    content: "Me 1 year ago: \"I need 100K followers to make money.\"\nMe now: Making $15K/month with 12K followers.\n\nThe secret? Stop obsessing over follower count. Start obsessing over:\n- How well you know your audience\n- How often you talk to them in DMs\n- How specific your offer is\n\nSmall audience + deep trust = big revenue.",
    publishedAt: "2025-01-28T15:30:00Z",
    likes: 7234,
    comments: 945,
    shares: 1876,
    impressions: 345000,
    reach: 234000,
    engagementRate: 11.2,
    isTopPerformer: true,
    accountUsername: "tami.young",
  },
  {
    id: "post-10",
    platform: "twitter",
    content: "Thread: 10 hooks that got me my highest engagement ever 🧵\n\n1/ \"The biggest lie in [industry] is...\"\n2/ \"I spent $X on Y. Here's what happened.\"\n3/ \"Stop doing X. Do Y instead.\"\n4/ \"Everyone is talking about X. Nobody is talking about Y.\"\n5/ \"I analyzed 100 [things]. Here's what I found.\"",
    publishedAt: "2025-01-25T12:00:00Z",
    likes: 3456,
    comments: 478,
    shares: 1234,
    impressions: 189000,
    reach: 134000,
    engagementRate: 7.9,
    isTopPerformer: true,
    accountUsername: "@tamiyoung",
  },
  {
    id: "post-11",
    platform: "linkedin",
    content: "I interviewed 20 creators who make $10K+/month.\n\nThey all had one thing in common:\n\nThey don't create content. They document their journey.\n\nBig difference.\n\nContent creation feels forced.\nDocumentation feels authentic.\n\nYour audience can feel the difference.",
    publishedAt: "2025-01-22T09:15:00Z",
    likes: 3890,
    comments: 567,
    shares: 890,
    impressions: 198000,
    reach: 142000,
    engagementRate: 8.5,
    isTopPerformer: true,
    accountUsername: "Tami Young",
  },
  {
    id: "post-12",
    platform: "instagram",
    content: "Real talk: I almost quit posting 6 months ago.\n\nI was burnt out, my engagement dropped, and I felt like I was screaming into the void.\n\nThen I did something radical: I took 2 weeks off.\n\nWhen I came back, I only posted what excited ME.\n\nResult: Best month of engagement ever.\n\nSometimes stepping back is the best strategy.",
    publishedAt: "2025-01-18T18:00:00Z",
    likes: 4123,
    comments: 678,
    shares: 987,
    impressions: 213000,
    reach: 156000,
    engagementRate: 8.9,
    isTopPerformer: true,
    accountUsername: "tami.young",
  },
];

export const mockTemplates: Template[] = [
  {
    id: "tmpl-1",
    name: "The Myth Buster",
    description: "Challenge a common belief, then reveal the truth with a personal story",
    content: "The biggest myth in [industry/topic]? That you need to [common belief].\n\nThe truth: [counter-intuitive insight].\n\nHere's what I learned after [personal achievement/experience]:",
    category: "hook",
    platform: null,
    tags: ["engagement", "storytelling", "authority"],
    sourcePostIds: ["post-1"],
    isAiGenerated: true,
    usageCount: 12,
    explanation: "This pattern works because it creates cognitive dissonance — the reader expects one thing but gets the opposite. The personal proof point adds credibility.",
    placeholders: ["industry/topic", "common belief", "counter-intuitive insight", "personal achievement/experience"],
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-20T00:00:00Z",
  },
  {
    id: "tmpl-2",
    name: "The Numbered List",
    description: "Share learnings or truths as a numbered list with a CTA at the end",
    content: "After [time period] of [activity], here are [N] uncomfortable truths:\n\n1. [Truth 1]\n2. [Truth 2]\n3. [Truth 3]\n4. [Truth 4]\n5. [Truth 5]\n\nWhich one resonates most? Drop the number below.",
    category: "engagement",
    platform: "linkedin",
    tags: ["list", "engagement", "CTA"],
    sourcePostIds: ["post-5"],
    isAiGenerated: true,
    usageCount: 8,
    explanation: "Numbered lists are highly shareable and the 'drop the number' CTA drives massive comment engagement because it's a low-effort action.",
    placeholders: ["time period", "activity", "N", "Truth 1-5"],
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-18T00:00:00Z",
  },
  {
    id: "tmpl-3",
    name: "The Before/After",
    description: "Contrast your past self with your current self to show transformation",
    content: "Me [time] ago: \"[old belief/situation]\"\nMe now: [new reality/result]\n\nThe secret? Stop obsessing over [vanity metric]. Start obsessing over:\n- [Real metric 1]\n- [Real metric 2]\n- [Real metric 3]\n\n[Punchy one-liner takeaway].",
    category: "story",
    platform: null,
    tags: ["transformation", "relatability", "insight"],
    sourcePostIds: ["post-9"],
    isAiGenerated: true,
    usageCount: 15,
    explanation: "Before/after framing instantly shows value and makes the reader imagine their own transformation. The specificity of the 'secret' makes it actionable.",
    placeholders: ["time", "old belief/situation", "new reality/result", "vanity metric", "Real metrics 1-3", "takeaway"],
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
];

export function formatNumber(num: number): string {
  if (num >= 1000000) return (num / 1000000).toFixed(1) + "M";
  if (num >= 1000) return (num / 1000).toFixed(1) + "K";
  return num.toString();
}

export function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
