import type { Photographer } from "./types";

export const PHOTOGRAPHERS: Photographer[] = [
  {
    id: "ansel-adams",
    name: "Ansel Adams",
    era: "1902–1984",
    country: "USA",
    styles: ["landscape", "fine-art"],
    signature: "Sweeping black-and-white American wilderness with crystalline tonal range.",
    bio: "Co-developer of the Zone System; his Yosemite and Sierra Nevada work defined modern landscape photography.",
    sampleSeeds: ["adams-1", "adams-2", "adams-3", "adams-4"],
  },
  {
    id: "vivian-maier",
    name: "Vivian Maier",
    era: "1926–2009",
    country: "USA",
    styles: ["street", "portrait"],
    signature: "Self-taught Chicago street photographer with sharp framing and quiet humanism.",
    bio: "Her work was discovered posthumously in a storage locker, revealing tens of thousands of frames of mid-century American life.",
    sampleSeeds: ["maier-1", "maier-2", "maier-3", "maier-4"],
  },
  {
    id: "henri-cartier-bresson",
    name: "Henri Cartier-Bresson",
    era: "1908–2004",
    country: "France",
    styles: ["street", "photojournalism", "documentary"],
    signature: "The “decisive moment” — geometry, gesture, and timing fused into one frame.",
    bio: "Co-founder of Magnum Photos; his 35mm Leica reportage shaped how generations frame the everyday.",
    sampleSeeds: ["hcb-1", "hcb-2", "hcb-3", "hcb-4"],
  },
  {
    id: "steve-mccurry",
    name: "Steve McCurry",
    era: "1950–",
    country: "USA",
    styles: ["portrait", "travel", "photojournalism"],
    signature: "Saturated, eye-locked portraits from across South Asia and beyond.",
    bio: "Best known for ‘Afghan Girl’ and decades of National Geographic assignments emphasizing color and human gaze.",
    sampleSeeds: ["mccurry-1", "mccurry-2", "mccurry-3", "mccurry-4"],
  },
  {
    id: "annie-leibovitz",
    name: "Annie Leibovitz",
    era: "1949–",
    country: "USA",
    styles: ["portrait", "fashion"],
    signature: "Theatrical, narrative celebrity portraiture with painterly lighting.",
    bio: "From Rolling Stone to Vanity Fair, her staged conceptual portraits define a generation of editorial work.",
    sampleSeeds: ["leibovitz-1", "leibovitz-2", "leibovitz-3", "leibovitz-4"],
  },
  {
    id: "richard-avedon",
    name: "Richard Avedon",
    era: "1923–2004",
    country: "USA",
    styles: ["portrait", "fashion"],
    signature: "Stark white-seamless portraits stripped of context — face as everything.",
    bio: "His ‘In the American West’ series reshaped portraiture, finding monumentality in ordinary subjects.",
    sampleSeeds: ["avedon-1", "avedon-2", "avedon-3", "avedon-4"],
  },
  {
    id: "sebastiao-salgado",
    name: "Sebastião Salgado",
    era: "1944–",
    country: "Brazil",
    styles: ["documentary", "photojournalism", "landscape"],
    signature: "Epic black-and-white reportage of labor, migration, and the natural world.",
    bio: "An economist turned photographer; ‘Workers’, ‘Migrations’, and ‘Genesis’ pair documentary rigor with high contrast grandeur.",
    sampleSeeds: ["salgado-1", "salgado-2", "salgado-3", "salgado-4"],
  },
  {
    id: "diane-arbus",
    name: "Diane Arbus",
    era: "1923–1971",
    country: "USA",
    styles: ["portrait", "documentary"],
    signature: "Square-format, flash-lit portraits of people on society’s margins.",
    bio: "Her unflinching encounters with strangers became a foundation of contemporary portraiture.",
    sampleSeeds: ["arbus-1", "arbus-2", "arbus-3", "arbus-4"],
  },
  {
    id: "saul-leiter",
    name: "Saul Leiter",
    era: "1923–2013",
    country: "USA",
    styles: ["street", "fine-art"],
    signature: "Painterly color street work — reflections, rain, and obscured layers.",
    bio: "An early adopter of color in art photography; his New York frames feel more like quiet paintings than reportage.",
    sampleSeeds: ["leiter-1", "leiter-2", "leiter-3", "leiter-4"],
  },
  {
    id: "daido-moriyama",
    name: "Daido Moriyama",
    era: "1938–",
    country: "Japan",
    styles: ["street"],
    signature: "Are-bure-boke — grainy, blurry, tilted Tokyo nights.",
    bio: "A central figure of Japan’s Provoke era, his raw black-and-white work redefined street photography.",
    sampleSeeds: ["moriyama-1", "moriyama-2", "moriyama-3", "moriyama-4"],
  },
  {
    id: "fan-ho",
    name: "Fan Ho",
    era: "1931–2016",
    country: "Hong Kong",
    styles: ["street", "fine-art"],
    signature: "Geometric beams of light slicing through 1950s Hong Kong alleys.",
    bio: "Filmmaker and photographer whose graphic, near-cinematic compositions are studies in light and shadow.",
    sampleSeeds: ["fanho-1", "fanho-2", "fanho-3", "fanho-4"],
  },
  {
    id: "william-eggleston",
    name: "William Eggleston",
    era: "1939–",
    country: "USA",
    styles: ["fine-art", "street"],
    signature: "Mundane Southern subjects elevated by saturated dye-transfer color.",
    bio: "His 1976 MoMA show legitimized color photography as fine art and made the everyday strange.",
    sampleSeeds: ["eggleston-1", "eggleston-2", "eggleston-3", "eggleston-4"],
  },
  {
    id: "helmut-newton",
    name: "Helmut Newton",
    era: "1920–2004",
    country: "Germany",
    styles: ["fashion", "portrait"],
    signature: "High-gloss, provocative black-and-white fashion staged like film stills.",
    bio: "Defined a hard-edged glamour for Vogue and beyond, balancing eroticism with cinematic precision.",
    sampleSeeds: ["newton-1", "newton-2", "newton-3", "newton-4"],
  },
  {
    id: "irving-penn",
    name: "Irving Penn",
    era: "1917–2009",
    country: "USA",
    styles: ["portrait", "still-life", "fashion"],
    signature: "Studio precision — clean backdrops, exquisite tonality, sculptural lighting.",
    bio: "His Vogue covers, ethnographic ‘Worlds in a Small Room’ portraits, and still lifes set the standard for studio craft.",
    sampleSeeds: ["penn-1", "penn-2", "penn-3", "penn-4"],
  },
  {
    id: "andreas-gursky",
    name: "Andreas Gursky",
    era: "1955–",
    country: "Germany",
    styles: ["landscape", "architecture", "fine-art"],
    signature: "Massive, hyper-detailed tableaus of contemporary scale — stock floors, supermarkets, rivers.",
    bio: "A Düsseldorf School heir whose digitally constructed prints meditate on globalization and pattern.",
    sampleSeeds: ["gursky-1", "gursky-2", "gursky-3", "gursky-4"],
  },
  {
    id: "gregory-crewdson",
    name: "Gregory Crewdson",
    era: "1962–",
    country: "USA",
    styles: ["fine-art", "portrait"],
    signature: "Cinematic, film-crew-scale tableaus of suburban unease.",
    bio: "Each image is staged like a movie set; series like ‘Beneath the Roses’ blur photography and narrative cinema.",
    sampleSeeds: ["crewdson-1", "crewdson-2", "crewdson-3", "crewdson-4"],
  },
  {
    id: "nick-brandt",
    name: "Nick Brandt",
    era: "1964–",
    country: "UK",
    styles: ["wildlife", "fine-art"],
    signature: "Reverent black-and-white portraits of East African megafauna.",
    bio: "Shot on medium-format film without telephoto lenses, his work treats animals as subjects of formal portraiture.",
    sampleSeeds: ["brandt-1", "brandt-2", "brandt-3", "brandt-4"],
  },
  {
    id: "joel-meyerowitz",
    name: "Joel Meyerowitz",
    era: "1938–",
    country: "USA",
    styles: ["street", "landscape"],
    signature: "Color street work and luminous Cape Cod beach studies.",
    bio: "An evangelist for color when it was still considered un-serious; equally fluent in 35mm street and 8x10 view-camera coastlines.",
    sampleSeeds: ["meyerowitz-1", "meyerowitz-2", "meyerowitz-3", "meyerowitz-4"],
  },
  {
    id: "hiroshi-sugimoto",
    name: "Hiroshi Sugimoto",
    era: "1948–",
    country: "Japan",
    styles: ["fine-art", "architecture", "landscape"],
    signature: "Long-exposure seascapes and dissolving architectural forms.",
    bio: "His conceptual series — ‘Theaters’, ‘Seascapes’, ‘Architecture’ — use time itself as a compositional tool.",
    sampleSeeds: ["sugimoto-1", "sugimoto-2", "sugimoto-3", "sugimoto-4"],
  },
  {
    id: "garry-winogrand",
    name: "Garry Winogrand",
    era: "1928–1984",
    country: "USA",
    styles: ["street", "documentary"],
    signature: "Tilted, restless 35mm frames documenting postwar America.",
    bio: "Shot more than a quarter-million frames left undeveloped at his death; an obsessive chronicler of public life.",
    sampleSeeds: ["winogrand-1", "winogrand-2", "winogrand-3", "winogrand-4"],
  },
];

export function sampleUrl(seed: string, w = 600, h = 400): string {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`;
}

export const ALL_STYLES = Array.from(
  new Set(PHOTOGRAPHERS.flatMap((p) => p.styles)),
).sort();
