import type { Photographer } from "./types";

export const PHOTOGRAPHERS: Photographer[] = [
  {
    id: "ansel-adams",
    name: "Ansel Adams",
    era: "1902–1984",
    country: "USA",
    styles: ["landscape", "fine-art"],
    moods: ["dramatic", "serene"],
    signature: "Sweeping black-and-white American wilderness with crystalline tonal range.",
    bio: "Co-developer of the Zone System; his Yosemite and Sierra Nevada work defined modern landscape photography.",
    wikipediaTitle: "Ansel_Adams",
    quote: "You don't take a photograph, you make it.",
  },
  {
    id: "vivian-maier",
    name: "Vivian Maier",
    era: "1926–2009",
    country: "USA",
    styles: ["street", "portrait"],
    moods: ["intimate", "melancholic"],
    signature: "Self-taught Chicago street photographer with sharp framing and quiet humanism.",
    bio: "Her work was discovered posthumously in a storage locker, revealing tens of thousands of frames of mid-century American life.",
    wikipediaTitle: "Vivian_Maier",
  },
  {
    id: "henri-cartier-bresson",
    name: "Henri Cartier-Bresson",
    era: "1908–2004",
    country: "France",
    styles: ["street", "photojournalism", "documentary"],
    moods: ["energetic", "minimal"],
    signature: "The “decisive moment” — geometry, gesture, and timing fused into one frame.",
    bio: "Co-founder of Magnum Photos; his 35mm Leica reportage shaped how generations frame the everyday.",
    wikipediaTitle: "Henri_Cartier-Bresson",
    quote: "Your first 10,000 photographs are your worst.",
  },
  {
    id: "steve-mccurry",
    name: "Steve McCurry",
    era: "1950–",
    country: "USA",
    styles: ["portrait", "travel", "photojournalism"],
    moods: ["bright", "dramatic", "intimate"],
    signature: "Saturated, eye-locked portraits from across South Asia and beyond.",
    bio: "Best known for ‘Afghan Girl’ and decades of National Geographic assignments emphasizing color and human gaze.",
    wikipediaTitle: "Steve_McCurry",
  },
  {
    id: "annie-leibovitz",
    name: "Annie Leibovitz",
    era: "1949–",
    country: "USA",
    styles: ["portrait", "fashion"],
    moods: ["dramatic", "moody"],
    signature: "Theatrical, narrative celebrity portraiture with painterly lighting.",
    bio: "From Rolling Stone to Vanity Fair, her staged conceptual portraits define a generation of editorial work.",
    wikipediaTitle: "Annie_Leibovitz",
  },
  {
    id: "richard-avedon",
    name: "Richard Avedon",
    era: "1923–2004",
    country: "USA",
    styles: ["portrait", "fashion"],
    moods: ["minimal", "intimate", "dramatic"],
    signature: "Stark white-seamless portraits stripped of context — face as everything.",
    bio: "His ‘In the American West’ series reshaped portraiture, finding monumentality in ordinary subjects.",
    wikipediaTitle: "Richard_Avedon",
    quote: "All photographs are accurate. None of them is the truth.",
  },
  {
    id: "sebastiao-salgado",
    name: "Sebastião Salgado",
    era: "1944–",
    country: "Brazil",
    styles: ["documentary", "photojournalism", "landscape"],
    moods: ["dramatic", "melancholic"],
    signature: "Epic black-and-white reportage of labor, migration, and the natural world.",
    bio: "An economist turned photographer; ‘Workers’, ‘Migrations’, and ‘Genesis’ pair documentary rigor with high contrast grandeur.",
    wikipediaTitle: "Sebastião_Salgado",
  },
  {
    id: "diane-arbus",
    name: "Diane Arbus",
    era: "1923–1971",
    country: "USA",
    styles: ["portrait", "documentary"],
    moods: ["intimate", "moody", "melancholic"],
    signature: "Square-format, flash-lit portraits of people on society’s margins.",
    bio: "Her unflinching encounters with strangers became a foundation of contemporary portraiture.",
    wikipediaTitle: "Diane_Arbus",
    quote: "A photograph is a secret about a secret.",
  },
  {
    id: "saul-leiter",
    name: "Saul Leiter",
    era: "1923–2013",
    country: "USA",
    styles: ["street", "fine-art"],
    moods: ["moody", "serene", "intimate"],
    signature: "Painterly color street work — reflections, rain, and obscured layers.",
    bio: "An early adopter of color in art photography; his New York frames feel more like quiet paintings than reportage.",
    wikipediaTitle: "Saul_Leiter",
    quote: "I happen to believe in the beauty of simple things.",
  },
  {
    id: "daido-moriyama",
    name: "Daido Moriyama",
    era: "1938–",
    country: "Japan",
    styles: ["street"],
    moods: ["moody", "energetic", "dramatic"],
    signature: "Are-bure-boke — grainy, blurry, tilted Tokyo nights.",
    bio: "A central figure of Japan’s Provoke era, his raw black-and-white work redefined street photography.",
    wikipediaTitle: "Daidō_Moriyama",
  },
  {
    id: "fan-ho",
    name: "Fan Ho",
    era: "1931–2016",
    country: "Hong Kong",
    styles: ["street", "fine-art"],
    moods: ["dramatic", "minimal", "serene"],
    signature: "Geometric beams of light slicing through 1950s Hong Kong alleys.",
    bio: "Filmmaker and photographer whose graphic, near-cinematic compositions are studies in light and shadow.",
    wikipediaTitle: "Fan_Ho",
  },
  {
    id: "william-eggleston",
    name: "William Eggleston",
    era: "1939–",
    country: "USA",
    styles: ["fine-art", "street"],
    moods: ["bright", "melancholic"],
    signature: "Mundane Southern subjects elevated by saturated dye-transfer color.",
    bio: "His 1976 MoMA show legitimized color photography as fine art and made the everyday strange.",
    wikipediaTitle: "William_Eggleston",
    quote: "I am at war with the obvious.",
  },
  {
    id: "helmut-newton",
    name: "Helmut Newton",
    era: "1920–2004",
    country: "Germany",
    styles: ["fashion", "portrait"],
    moods: ["dramatic", "moody"],
    signature: "High-gloss, provocative black-and-white fashion staged like film stills.",
    bio: "Defined a hard-edged glamour for Vogue and beyond, balancing eroticism with cinematic precision.",
    wikipediaTitle: "Helmut_Newton",
  },
  {
    id: "irving-penn",
    name: "Irving Penn",
    era: "1917–2009",
    country: "USA",
    styles: ["portrait", "still-life", "fashion"],
    moods: ["minimal", "serene"],
    signature: "Studio precision — clean backdrops, exquisite tonality, sculptural lighting.",
    bio: "His Vogue covers, ethnographic ‘Worlds in a Small Room’ portraits, and still lifes set the standard for studio craft.",
    wikipediaTitle: "Irving_Penn",
  },
  {
    id: "andreas-gursky",
    name: "Andreas Gursky",
    era: "1955–",
    country: "Germany",
    styles: ["landscape", "architecture", "fine-art"],
    moods: ["minimal", "dramatic"],
    contemporary: true,
    signature: "Massive, hyper-detailed tableaus of contemporary scale — stock floors, supermarkets, rivers.",
    bio: "A Düsseldorf School heir whose digitally constructed prints meditate on globalization and pattern.",
    wikipediaTitle: "Andreas_Gursky",
  },
  {
    id: "gregory-crewdson",
    name: "Gregory Crewdson",
    era: "1962–",
    country: "USA",
    styles: ["fine-art", "portrait"],
    moods: ["moody", "dramatic", "melancholic"],
    contemporary: true,
    signature: "Cinematic, film-crew-scale tableaus of suburban unease.",
    bio: "Each image is staged like a movie set; series like ‘Beneath the Roses’ blur photography and narrative cinema.",
    wikipediaTitle: "Gregory_Crewdson",
    quote: "Every artist has a central story to tell.",
  },
  {
    id: "nick-brandt",
    name: "Nick Brandt",
    era: "1964–",
    country: "UK",
    styles: ["wildlife", "fine-art"],
    moods: ["dramatic", "melancholic", "serene"],
    contemporary: true,
    signature: "Reverent black-and-white portraits of East African megafauna.",
    bio: "Shot on medium-format film without telephoto lenses, his work treats animals as subjects of formal portraiture.",
    wikipediaTitle: "Nick_Brandt",
  },
  {
    id: "joel-meyerowitz",
    name: "Joel Meyerowitz",
    era: "1938–",
    country: "USA",
    styles: ["street", "landscape"],
    moods: ["bright", "serene", "energetic"],
    signature: "Color street work and luminous Cape Cod beach studies.",
    bio: "An evangelist for color when it was still considered un-serious; equally fluent in 35mm street and 8x10 view-camera coastlines.",
    wikipediaTitle: "Joel_Meyerowitz",
  },
  {
    id: "hiroshi-sugimoto",
    name: "Hiroshi Sugimoto",
    era: "1948–",
    country: "Japan",
    styles: ["fine-art", "architecture", "landscape"],
    moods: ["minimal", "serene", "melancholic"],
    contemporary: true,
    signature: "Long-exposure seascapes and dissolving architectural forms.",
    bio: "His conceptual series — ‘Theaters’, ‘Seascapes’, ‘Architecture’ — use time itself as a compositional tool.",
    wikipediaTitle: "Hiroshi_Sugimoto",
    quote: "Time exposed is what photography really is.",
  },
  {
    id: "garry-winogrand",
    name: "Garry Winogrand",
    era: "1928–1984",
    country: "USA",
    styles: ["street", "documentary"],
    moods: ["energetic"],
    signature: "Tilted, restless 35mm frames documenting postwar America.",
    bio: "Shot more than a quarter-million frames left undeveloped at his death; an obsessive chronicler of public life.",
    wikipediaTitle: "Garry_Winogrand",
    quote: "I photograph to see what something will look like photographed.",
  },

  /* ===== Contemporary voices ===== */

  {
    id: "alec-soth",
    name: "Alec Soth",
    era: "1969–",
    country: "USA",
    styles: ["documentary", "portrait", "fine-art"],
    moods: ["melancholic", "intimate", "serene"],
    contemporary: true,
    signature: "Lyrical large-format road trips through overlooked America.",
    bio: "His Magnum-era books — ‘Sleeping by the Mississippi’, ‘Niagara’, ‘Songbook’ — turned the photo book into the defining format of contemporary documentary.",
    wikipediaTitle: "Alec_Soth",
  },
  {
    id: "nan-goldin",
    name: "Nan Goldin",
    era: "1953–",
    country: "USA",
    styles: ["documentary", "portrait", "fine-art"],
    moods: ["intimate", "moody"],
    contemporary: true,
    signature: "Diaristic, flash-lit color of chosen family, love, and loss.",
    bio: "‘The Ballad of Sexual Dependency’ made the personal snapshot a fine-art form; her influence runs through nearly all confessional photography since.",
    wikipediaTitle: "Nan_Goldin",
  },
  {
    id: "alex-webb",
    name: "Alex Webb",
    era: "1952–",
    country: "USA",
    styles: ["street", "photojournalism", "travel"],
    moods: ["energetic", "dramatic", "bright"],
    contemporary: true,
    signature: "Dense, layered color frames built from harsh light and deep shadow.",
    bio: "A Magnum member whose work in Haiti, Mexico, and along borders compresses multiple stories into single, overflowing compositions.",
    wikipediaTitle: "Alex_Webb_(photographer)",
  },
  {
    id: "wolfgang-tillmans",
    name: "Wolfgang Tillmans",
    era: "1968–",
    country: "Germany",
    styles: ["fine-art", "portrait", "still-life", "abstract"],
    moods: ["bright", "minimal", "intimate"],
    contemporary: true,
    signature: "Casual-looking but rigorously seen images of friends, fruit, and pure light.",
    bio: "The first photographer to win the Turner Prize; moves freely between club culture portraiture, still life, and camera-less abstraction.",
    wikipediaTitle: "Wolfgang_Tillmans",
  },
  {
    id: "cindy-sherman",
    name: "Cindy Sherman",
    era: "1954–",
    country: "USA",
    styles: ["fine-art", "portrait"],
    moods: ["dramatic", "moody"],
    contemporary: true,
    signature: "Self-portraits as invented characters interrogating image culture.",
    bio: "‘Untitled Film Stills’ and decades of staged personae made her one of the most influential artists working in photography.",
    wikipediaTitle: "Cindy_Sherman",
  },
  {
    id: "tyler-mitchell",
    name: "Tyler Mitchell",
    era: "1995–",
    country: "USA",
    styles: ["fashion", "portrait", "fine-art"],
    moods: ["bright", "serene", "intimate"],
    contemporary: true,
    signature: "Sunlit, utopian imagery of Black life and leisure.",
    bio: "At 23 he became the first Black photographer to shoot an American Vogue cover (Beyoncé, 2018); his work moves between editorial and museum walls.",
    wikipediaTitle: "Tyler_Mitchell_(photographer)",
  },
  {
    id: "nadine-ijewere",
    name: "Nadine Ijewere",
    era: "1992–",
    country: "UK",
    styles: ["fashion", "portrait"],
    moods: ["bright", "energetic"],
    contemporary: true,
    signature: "Lush fashion imagery celebrating diaspora beauty and unconventional casting.",
    bio: "The first woman of color to shoot a British Vogue cover; her Jamaican-Nigerian heritage shapes a distinctly warm, pattern-rich editorial style.",
    wikipediaTitle: "Nadine_Ijewere",
  },
  {
    id: "petra-collins",
    name: "Petra Collins",
    era: "1992–",
    country: "Canada",
    styles: ["fashion", "fine-art", "portrait"],
    moods: ["intimate", "moody", "serene"],
    contemporary: true,
    signature: "Hazy, pastel dreamscapes of girlhood shot like half-remembered VHS.",
    bio: "From American Apparel campaigns to music videos and gallery shows, she defined the soft-focus aesthetic of a social-media generation.",
    wikipediaTitle: "Petra_Collins",
  },
  {
    id: "lynsey-addario",
    name: "Lynsey Addario",
    era: "1973–",
    country: "USA",
    styles: ["photojournalism", "documentary"],
    moods: ["dramatic", "intimate"],
    contemporary: true,
    signature: "Frontline conflict reportage centered on women's lives within war.",
    bio: "A MacArthur fellow and Pulitzer-winning team member who has covered Afghanistan, Libya, and Ukraine for The New York Times and National Geographic.",
    wikipediaTitle: "Lynsey_Addario",
  },
  {
    id: "paul-nicklen",
    name: "Paul Nicklen",
    era: "1968–",
    country: "Canada",
    styles: ["wildlife", "documentary"],
    moods: ["dramatic", "serene"],
    contemporary: true,
    signature: "Polar wildlife photographed at arm's length, above and below the ice.",
    bio: "National Geographic photographer and SeaLegacy co-founder whose leopard seal and emperor penguin work fuses conservation with intimacy.",
    wikipediaTitle: "Paul_Nicklen",
  },
  {
    id: "michael-kenna",
    name: "Michael Kenna",
    era: "1953–",
    country: "UK",
    styles: ["landscape", "fine-art"],
    moods: ["minimal", "serene", "melancholic"],
    contemporary: true,
    signature: "Spare, long-exposure black-and-white landscapes — a few trees, fog, silence.",
    bio: "His square Hasselblad studies of Hokkaido, industrial sites, and coastlines are touchstones of minimalist landscape photography.",
    wikipediaTitle: "Michael_Kenna_(photographer)",
  },
  {
    id: "trent-parke",
    name: "Trent Parke",
    era: "1971–",
    country: "Australia",
    styles: ["street", "fine-art", "documentary"],
    moods: ["dramatic", "moody"],
    contemporary: true,
    signature: "Hallucinatory Australian light — black-and-white street pushed to the edge of abstraction.",
    bio: "The only Australian member of Magnum; ‘Minutes to Midnight’ and ‘The Seventh Wave’ treat sunlight itself as the subject.",
    wikipediaTitle: "Trent_Parke",
  },
  {
    id: "rinko-kawauchi",
    name: "Rinko Kawauchi",
    era: "1972–",
    country: "Japan",
    styles: ["fine-art", "still-life", "macro"],
    moods: ["serene", "minimal", "bright"],
    contemporary: true,
    signature: "Luminous pastel fragments of the everyday — an egg, a swarm, a shaft of light.",
    bio: "‘Utatane’ and ‘Illuminance’ assemble small overexposed moments into something close to visual haiku.",
    wikipediaTitle: "Rinko_Kawauchi",
  },
  {
    id: "zanele-muholi",
    name: "Zanele Muholi",
    era: "1972–",
    country: "South Africa",
    styles: ["portrait", "documentary", "fine-art"],
    moods: ["dramatic", "intimate"],
    contemporary: true,
    signature: "High-contrast self-portraits and portraits asserting Black queer presence.",
    bio: "A self-described visual activist; the ongoing ‘Somnyama Ngonyama’ series turns everyday materials into regal, confrontational imagery.",
    wikipediaTitle: "Zanele_Muholi",
  },
  {
    id: "hassan-hajjaj",
    name: "Hassan Hajjaj",
    era: "1961–",
    country: "Morocco",
    styles: ["portrait", "fashion"],
    moods: ["energetic", "bright"],
    contemporary: true,
    signature: "Pop-saturated portraits framed in repurposed product packaging.",
    bio: "Often called the ‘Andy Warhol of Marrakech’; his ‘Kesh Angels’ biker series remixes street style, branding, and North African studio portraiture.",
    wikipediaTitle: "Hassan_Hajjaj",
  },
  {
    id: "levon-biss",
    name: "Levon Biss",
    era: "1975–",
    country: "UK",
    styles: ["macro", "still-life"],
    moods: ["minimal", "bright"],
    contemporary: true,
    signature: "Museum-scale insect portraits assembled from thousands of macro frames.",
    bio: "His ‘Microsculpture’ project photographs entomology collections at extreme magnification, printing beetles three meters tall.",
    wikipediaTitle: "Levon_Biss",
  },
  {
    id: "iwan-baan",
    name: "Iwan Baan",
    era: "1975–",
    country: "Netherlands",
    styles: ["architecture", "documentary", "travel"],
    moods: ["bright", "energetic"],
    contemporary: true,
    signature: "Architecture photographed as it's actually lived in — people first, buildings second.",
    bio: "The go-to photographer for contemporary architects worldwide; his informal, humane approach broke with sterile architectural tradition.",
    wikipediaTitle: "Iwan_Baan",
  },
];

export const ALL_STYLES = Array.from(
  new Set(PHOTOGRAPHERS.flatMap((p) => p.styles)),
).sort();
