import type { Folder } from "../types";

export const showingMyWork: Folder = {
  slug: "showing-my-work",
  name: "Showing my work",
  label: "WRITING",
  blurb: "Published writing: Buffer, clients, and the newsletter. Each file opens where it was published.",
  view: "list",
  accent: "blue",
  files: [
    {
      slug: "buffer-blog-sample",
      title: "A recommendations-first guide (Buffer blog)",
      kind: "article",
      publisher: "Buffer",
      date: "2026-09-01",
      url: "https://buffer.com/resources/",
      summary: "Practitioner-led, recommendations first. Swap this for a real post URL.",
      info: { Format: "Long-form guide", Role: "Writer and editor" },
      tags: ["blog"],
    },
    {
      slug: "buffer-newsletter-sample",
      title: "The Weekly Scroll (newsletter)",
      kind: "article",
      publisher: "Buffer",
      date: "2026-08-20",
      url: "https://buffer.com/",
      summary: "One of the recurring newsletters I write and edit at Buffer.",
      info: { Format: "Newsletter", Role: "Writer" },
      tags: ["newsletter"],
    },
    {
      slug: "client-sample",
      title: "Client piece (title withheld)",
      kind: "article",
      publisher: "Client",
      date: "2026-07-10",
      summary: "Ghostwritten long-form for a creator-economy tool. Ask me for the link.",
      info: { Format: "Ghostwritten essay", Role: "Writer" },
      tags: ["client"],
    },
    {
      slug: "substack-sample",
      title: "Notes on choosing your life (Substack)",
      kind: "article",
      publisher: "Substack",
      date: "2026-06-15",
      url: "https://substack.com/@tami",
      summary: "The newsletter under my own name. Issues, not posts.",
      info: { Format: "Newsletter issue", Role: "Everything" },
      tags: ["newsletter"],
    },
  ],
};
